ethereum_rpc = "https://0xrpc.io/hoodi"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.mev_sandwich]
path = "out/MEVSandwichTrap.sol/MEVSandwichTrap.json"

response_contract = "0x6dDfa8202215e70C097307531c99b881ED4212F8"
response_function = "respondToMEV(address,uint256,uint256,uint256,uint256)"

cooldown_period_blocks = 20
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 2

private_trap = true
whitelist = [""]
  
